# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-16 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='prof_pic',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
