# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-20 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0008_auto_20200219_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemerch',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProfileMerch',
        ),
    ]
